{% set version = "3.6.3" %}

package:
  name: arpack-mpi
  version: {{ version }}

source:
  fn: arpack-{{ version }}.tar.gz
  url: https://github.com/opencollab/arpack-ng/archive/{{ version }}.tar.gz
  sha256: 64f3551e5a2f8497399d82af3076b6a33bf1bc95fc46bbcabe66442db366f453

build:
  number: 0
  features:

requirements:
  build:
    - cmake
    - openmpi
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - libopenblas

test:
  commands:
    - test -f ${PREFIX}/lib/libarpack.a
    - test -f ${PREFIX}/lib/libparpack.a
    - test -f ${PREFIX}/lib/libarpack${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libparpack${SHLIB_EXT}

about:
  home: https://github.com/opencollab/arpack-ng
  license: BSD 3-Clause
  license_file: COPYING
  summary: Fortran77 subroutines designed to solve large scale eigenvalue problems

extra:
  recipe-maintainers:
    - jschueller
    - mrakitin
    - shenmidelin
