{% set year = "2019" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: 23-id-1-csx1-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - 23-id-1-csx1-analysis >=2019C2.0
    - hklpy >=0.3.13
    - hxntools
