{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "0" %}

package:
  name: 02-id-six-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - pycentroids
    - sixtools
