{% set version = "0.4.1" %}

package:
  name: atom
  version: {{ version }}

source:
  git_url: https://github.com/nucleic/atom
  git_rev: {{ version }}

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python

test:
  # Python imports
  imports:
    - atom
    - atom.datastructures
    - tests

about:
  home: https://github.com/nucleic/atom
  license: Modified BSD
  summary: 'Memory efficient Python objects'
